// Code generated by github.com/hinego/gen. DO NOT EDIT.
// Code generated by github.com/hinego/gen. DO NOT EDIT.
// Code generated by github.com/hinego/gen. DO NOT EDIT.

package model

const TableNameModel = "models"

// Model mapped from table <models>
type Model struct {
	ID        int64 `gorm:"column:id;type:integer;primaryKey" json:"id"`
	CreatedAt int64 `gorm:"column:created_at;type:integer;not null" json:"created_at"`
	UpdatedAt int64 `gorm:"column:updated_at;type:integer;not null" json:"updated_at"`
}

// TableName Model's table name
func (*Model) TableName() string {
	return TableNameModel
}
