// Code generated by github.com/hinego/gen. DO NOT EDIT.
// Code generated by github.com/hinego/gen. DO NOT EDIT.
// Code generated by github.com/hinego/gen. DO NOT EDIT.

package model

import "github.com/sucold/starter/app/conset/tab"

const TableNameService = "services"

// Service mapped from table <services>
type Service struct {
	ID        int64             `gorm:"column:id;type:integer;primaryKey" json:"id"`
	CreatedAt int64             `gorm:"column:created_at;type:integer;not null" json:"created_at"`
	UpdatedAt int64             `gorm:"column:updated_at;type:integer;not null" json:"updated_at"`
	Code      string            `gorm:"column:code;type:text;not null" json:"code"`
	Name      string            `gorm:"column:name;type:text;not null" json:"name"`
	Desc      string            `gorm:"column:desc;type:text;not null" json:"desc"`
	Status    tab.ServiceStatus `gorm:"column:status;type:text;not null" json:"status" field:"string"`
	Text      string            `gorm:"column:text;type:text;not null" json:"text"`
	Auto      bool              `gorm:"column:auto;type:numeric;not null" json:"auto" dc:"自动启动"`
	Data      string            `gorm:"column:data;type:text;not null" json:"data" dc:"服务的持久化数据"`
	BootTime  int64             `gorm:"column:boot_time;type:integer;not null" json:"boot_time" dc:"启动时间"`
	StopTime  int64             `gorm:"column:stop_time;type:integer;not null" json:"stop_time" dc:"停止时间"`
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
