// Code generated by github.com/hinego/gen. DO NOT EDIT.
// Code generated by github.com/hinego/gen. DO NOT EDIT.
// Code generated by github.com/hinego/gen. DO NOT EDIT.

package model

import "github.com/hinego/decimal"

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt int64           `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64           `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	Name      string          `gorm:"column:name;type:text" json:"name"`
	Email     string          `gorm:"column:email;type:text;uniqueIndex:users_email_key,priority:1" json:"email"`
	Password  string          `gorm:"column:password;type:text" json:"password"`
	Balance   decimal.Decimal `gorm:"column:balance;type:numeric" json:"balance" dc:"用户余额"`
	Refer     int64           `gorm:"column:refer;type:bigint" json:"refer"`
	IP        string          `gorm:"column:ip;type:text" json:"ip" dc:"注册IP"`
	Role      string          `gorm:"column:role;type:text" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
