// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBin = "bins"

// Bin mapped from table <bins>
type Bin struct {
	ID         int64  `gorm:"column:id;type:integer;primaryKey" json:"id"`
	CreatedAt  int64  `gorm:"column:created_at;type:integer;not null" json:"created_at"`
	UpdatedAt  int64  `gorm:"column:updated_at;type:integer;not null" json:"updated_at"`
	Card       string `gorm:"column:card;type:text;not null" json:"card"`
	Code       int64  `gorm:"column:code;type:integer;not null" json:"code"`
	Vendor     string `gorm:"column:vendor;type:text;not null" json:"vendor"`
	Country    string `gorm:"column:country;type:text;not null" json:"country"`
	Emoji      string `gorm:"column:emoji;type:text;not null" json:"emoji"`
	BankLogo   string `gorm:"column:bank_logo;type:text;not null" json:"bank_logo"`
	CountryCn  string `gorm:"column:country_cn;type:text;not null" json:"country_cn"`
	Country2   string `gorm:"column:country2;type:text;not null" json:"country2"`
	Country3   string `gorm:"column:country3;type:text;not null" json:"country3"`
	Symbol     string `gorm:"column:symbol;type:text;not null" json:"symbol"`
	Level      string `gorm:"column:level;type:text;not null" json:"level"`
	Rank       string `gorm:"column:rank;type:text;not null" json:"rank"`
	Bank       string `gorm:"column:bank;type:text;not null" json:"bank"`
	PassVbv    string `gorm:"column:pass_vbv;type:text;not null" json:"pass_vbv"`
	Remark     string `gorm:"column:remark;type:text;not null" json:"remark"`
	Website    string `gorm:"column:website;type:text;not null" json:"website"`
	Phone      string `gorm:"column:phone;type:text;not null" json:"phone"`
	User       string `gorm:"column:user;type:text;not null" json:"user"`
	UpdateTime int64  `gorm:"column:update_time;type:integer;not null" json:"update_time"`
}

// TableName Bin's table name
func (*Bin) TableName() string {
	return TableNameBin
}
