// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	ID         int64  `gorm:"column:id;type:integer;primaryKey" json:"id"`
	CreatedAt  int64  `gorm:"column:created_at;type:integer;not null" json:"created_at"`
	UpdatedAt  int64  `gorm:"column:updated_at;type:integer;not null" json:"updated_at"`
	Name       string `gorm:"column:name;type:text;not null" json:"name"`
	File       string `gorm:"column:file;type:text;not null" json:"file"`
	User       string `gorm:"column:user;type:text;not null" json:"user"`
	Remark     string `gorm:"column:remark;type:text;not null" json:"remark"`
	UpdateTime int64  `gorm:"column:update_time;type:integer;not null" json:"update_time"`
	Size       int64  `gorm:"column:size;type:integer;not null" json:"size"`
	Number     int64  `gorm:"column:number;type:integer;not null" json:"number"`
	Split      string `gorm:"column:split;type:text;not null" json:"split"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
