// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/hinego/systemd/internal/model"
)

func newTransform(db *gorm.DB, opts ...gen.DOOption) transform {
	_transform := transform{}

	_transform.transformDo.UseDB(db, opts...)
	_transform.transformDo.UseModel(&model.Transform{})

	tableName := _transform.transformDo.TableName()
	_transform.ALL = field.NewAsterisk(tableName)
	_transform.ID = field.NewInt64(tableName, "id")
	_transform.CreatedAt = field.NewInt64(tableName, "created_at")
	_transform.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_transform.UserID = field.NewInt64(tableName, "user_id")
	_transform.Name = field.NewString(tableName, "name")
	_transform.File = field.NewString(tableName, "file")
	_transform.Size = field.NewInt64(tableName, "size")
	_transform.Remark = field.NewString(tableName, "remark")
	_transform.Number = field.NewInt64(tableName, "number")
	_transform.Split = field.NewString(tableName, "split")

	_transform.fillFieldMap()

	return _transform
}

type transform struct {
	transformDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Int64
	UpdatedAt field.Int64
	UserID    field.Int64
	Name      field.String
	File      field.String
	Size      field.Int64
	Remark    field.String
	Number    field.Int64
	Split     field.String

	fieldMap map[string]field.Expr
}

func (t transform) Table(newTableName string) *transform {
	t.transformDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transform) As(alias string) *transform {
	t.transformDo.DO = *(t.transformDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transform) updateTableName(table string) *transform {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.UserID = field.NewInt64(table, "user_id")
	t.Name = field.NewString(table, "name")
	t.File = field.NewString(table, "file")
	t.Size = field.NewInt64(table, "size")
	t.Remark = field.NewString(table, "remark")
	t.Number = field.NewInt64(table, "number")
	t.Split = field.NewString(table, "split")

	t.fillFieldMap()

	return t
}

func (t *transform) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transform) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["name"] = t.Name
	t.fieldMap["file"] = t.File
	t.fieldMap["size"] = t.Size
	t.fieldMap["remark"] = t.Remark
	t.fieldMap["number"] = t.Number
	t.fieldMap["split"] = t.Split
}

func (t transform) clone(db *gorm.DB) transform {
	t.transformDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t transform) replaceDB(db *gorm.DB) transform {
	t.transformDo.ReplaceDB(db)
	return t
}

type transformDo struct{ gen.DO }

func (t transformDo) Debug() *transformDo {
	return t.withDO(t.DO.Debug())
}

func (t transformDo) WithContext(ctx context.Context) *transformDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transformDo) ReadDB() *transformDo {
	return t.Clauses(dbresolver.Read)
}

func (t transformDo) WriteDB() *transformDo {
	return t.Clauses(dbresolver.Write)
}

func (t transformDo) Session(config *gorm.Session) *transformDo {
	return t.withDO(t.DO.Session(config))
}

func (t transformDo) Clauses(conds ...clause.Expression) *transformDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transformDo) Returning(value interface{}, columns ...string) *transformDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transformDo) Not(conds ...gen.Condition) *transformDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transformDo) Or(conds ...gen.Condition) *transformDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transformDo) Select(conds ...field.Expr) *transformDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transformDo) Where(conds ...gen.Condition) *transformDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transformDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *transformDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t transformDo) Order(conds ...field.Expr) *transformDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transformDo) Distinct(cols ...field.Expr) *transformDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transformDo) Omit(cols ...field.Expr) *transformDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transformDo) Join(table schema.Tabler, on ...field.Expr) *transformDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transformDo) LeftJoin(table schema.Tabler, on ...field.Expr) *transformDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transformDo) RightJoin(table schema.Tabler, on ...field.Expr) *transformDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transformDo) Group(cols ...field.Expr) *transformDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transformDo) Having(conds ...gen.Condition) *transformDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transformDo) Limit(limit int) *transformDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transformDo) Offset(offset int) *transformDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transformDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *transformDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transformDo) Unscoped() *transformDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transformDo) Create(values ...*model.Transform) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transformDo) CreateInBatches(values []*model.Transform, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transformDo) Save(values ...*model.Transform) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transformDo) First() (*model.Transform, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Transform), nil
	}
}

func (t transformDo) Take() (*model.Transform, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Transform), nil
	}
}

func (t transformDo) Last() (*model.Transform, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Transform), nil
	}
}

func (t transformDo) Find() ([]*model.Transform, error) {
	result, err := t.DO.Find()
	return result.([]*model.Transform), err
}

func (t transformDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Transform, err error) {
	buf := make([]*model.Transform, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transformDo) FindInBatches(result *[]*model.Transform, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transformDo) Attrs(attrs ...field.AssignExpr) *transformDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transformDo) Assign(attrs ...field.AssignExpr) *transformDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transformDo) Joins(fields ...field.RelationField) *transformDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transformDo) Preload(fields ...field.RelationField) *transformDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transformDo) FirstOrInit() (*model.Transform, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Transform), nil
	}
}

func (t transformDo) FirstOrCreate() (*model.Transform, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Transform), nil
	}
}

func (t transformDo) FindByPage(offset int, limit int) (result []*model.Transform, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transformDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transformDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transformDo) Delete(models ...*model.Transform) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transformDo) withDO(do gen.Dao) *transformDo {
	t.DO = *do.(*gen.DO)
	return t
}
